POST http://localhost:3001/api  
Content-Type: application/json  

{
"name: "munashe" 
"email": "munashemadhuna@gmail.com"
}

Get http://localhost:3001/api 
Content-Type: application/json 


